// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: emailsender.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailSender_SendEventNotification_FullMethodName = "/api.EmailSender/SendEventNotification"
)

// EmailSenderClient is the client API for EmailSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailSenderClient interface {
	SendEventNotification(ctx context.Context, in *SendEventNotificationRequest, opts ...grpc.CallOption) (*SendEventNotificationResponse, error)
}

type emailSenderClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailSenderClient(cc grpc.ClientConnInterface) EmailSenderClient {
	return &emailSenderClient{cc}
}

func (c *emailSenderClient) SendEventNotification(ctx context.Context, in *SendEventNotificationRequest, opts ...grpc.CallOption) (*SendEventNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEventNotificationResponse)
	err := c.cc.Invoke(ctx, EmailSender_SendEventNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailSenderServer is the server API for EmailSender service.
// All implementations must embed UnimplementedEmailSenderServer
// for forward compatibility.
type EmailSenderServer interface {
	SendEventNotification(context.Context, *SendEventNotificationRequest) (*SendEventNotificationResponse, error)
	mustEmbedUnimplementedEmailSenderServer()
}

// UnimplementedEmailSenderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailSenderServer struct{}

func (UnimplementedEmailSenderServer) SendEventNotification(context.Context, *SendEventNotificationRequest) (*SendEventNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEventNotification not implemented")
}
func (UnimplementedEmailSenderServer) mustEmbedUnimplementedEmailSenderServer() {}
func (UnimplementedEmailSenderServer) testEmbeddedByValue()                     {}

// UnsafeEmailSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailSenderServer will
// result in compilation errors.
type UnsafeEmailSenderServer interface {
	mustEmbedUnimplementedEmailSenderServer()
}

func RegisterEmailSenderServer(s grpc.ServiceRegistrar, srv EmailSenderServer) {
	// If the following call pancis, it indicates UnimplementedEmailSenderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailSender_ServiceDesc, srv)
}

func _EmailSender_SendEventNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEventNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailSenderServer).SendEventNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailSender_SendEventNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailSenderServer).SendEventNotification(ctx, req.(*SendEventNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailSender_ServiceDesc is the grpc.ServiceDesc for EmailSender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailSender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.EmailSender",
	HandlerType: (*EmailSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEventNotification",
			Handler:    _EmailSender_SendEventNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emailsender.proto",
}
